sudo: false
language: java
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
jobs:
  include:
    - stage: build
      script: mvn --quiet -B -DskipTests clean install dependency:resolve-plugins dependency:go-offline
    - stage: test
    - script: mvn -B -P jetty integration-test verify
    - script: mvn -B -P undertow integration-test verify
    - script: mvn -B -P tomcat integration-test verify
jdk:
  - oraclejdk8
notifications:
  email:
      - bcanhome@googlemail.com
