sudo: false
language: java
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: travis_wait 80 mvn --quiet -Ptravis,!load-test clean install
jdk:
  - oraclejdk8
notifications:
  email:
      - bcanhome@googlemail.com
